version: "3.8"
services:
  frontend:
    build: ./front-end/park-engage
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment: 
      - SERVER_ENDPOINT=http://localhost:5001/api/park

  backend:
    build: ./backend
    ports:
      - "5001:5001"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
