version: "3.8"
services:
  frontend:
    build: ./front-end/park-engage
    ports:
      - "3000:5173"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
